version: '3'
services:
  db:
    image: mysql:latest
    container_name: local-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - /home/sanjaykumar/Documents/Docker/mysql/db:/var/lib/mysql